config/routes.rb
Rails.application.routes.draw do
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :find_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:content)
  end

  def find_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Editer</h1>


<%= form_for @task do |f| %>
  <%= f.text_field :content %>
  <%= f.submit 'Creat task' %>
<% end %>

app/views/tasks/index.html.erb
<h1>Task list</h1>

<%= link_to 'Add Task', new_task_path %>

<% @tasks.each do |task| %>
  <div>
    <p><%= task.content %></p>
    <%= link_to 'View Task', task_path(task) %>
    <%= link_to 'Delete', task_path(task), method: :delete, data: { confirm: "Are you sure?" } %>
  </div>
<% end %>

app/views/tasks/new.html.erb
<h1>Add task</h1>

<%= form_for @task do |f| %>
  <%= f.text_field :content %>
  <%= f.submit 'Add' %>
<% end %>

app/views/tasks/show.html.erb
<h1>Task</h1>

<p>task.content</p>
<%= link_to 'Edit', edit_task_path(@task) %>

<%= link_to 'back to List', tasks_path %>